# Generated by Django 2.2.4 on 2021-02-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads_app', '0002_remove_book_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='notes',
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='newAuthor', max_length=100),
            preserve_default=False,
        ),
    ]
